---
abstract: 'Database independent interface for Perl'
author:
  - 'Tim Bunce (dbi-users@perl.org)'
build_requires:
  ExtUtils::MakeMaker: 6.48
  Test::Simple: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
conflicts:
  DBD::Amazon: 0.10
  DBD::AnyData: 0.110
  DBD::CSV: 0.36
  DBD::Google: 0.51
  DBD::PO: 2.10
  DBD::RAM: 0.072
  SQL::Statement: 1.33
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6501, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBI
no_index:
  directory:
    - t
    - inc
recommends:
  Clone: 0.34
  DB_File: 0
  MLDBM: 0
  Net::Daemon: 0
  RPC::PlServer: 0.2001
  SQL::Statement: 1.402
requires:
  perl: 5.008
resources:
  homepage: http://dbi.perl.org/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-dbi/dbi
  x_MailingList: mailto:dbi-dev@perl.org
version: 1.626
