#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBI
version:      1.38
version_from: DBI.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
